# -*- coding: utf-8 -*-
"""Projeto_analise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kw20nt7YvFxihBP6MenzcFV8tB1odg8

# Análise de Poluentes em São Paulo

Este notebook analisa dados da qualidade do ar em São Paulo, com foco nos poluentes MP10 e O₃. Vamos investigar padrões temporais e possíveis quedas durante a pandemia.

## Importação de bibliotecas e leitura dos dados
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
caminho = 'dados/SP_poluicao_dados.csv'
dados = pd.read_csv(caminho)

dados = dados.drop(columns = ['Unnamed: 0', 'ID'])

dados.head()

"""## Limpeza e preparação dos dados


"""

dados['DataHora'] = pd.to_datetime(dados['Data'] + ' ' + dados['Hora'])
print(dados.dtypes)
print(dados.isnull().sum())

"""## Análise dos tipos de poluentes"""

#Tipos de Poluentes em SP!
tipos_poluentes = dados['Poluente'].unique()
print('Tipos de poluentes que existem em SP: ', tipos_poluentes)
contagem_poluentes = (dados['Poluente']).value_counts()
print(contagem_poluentes)
contagem_poluentes.plot(kind = 'bar')
plt.title('Quantidade de medições por tipo de poluente')
plt.xlabel('Poluentes')
plt.ylabel('Quantidade')
#Vemos que o poluente que mais aparece seria o MP10 por ser um poluente feito por veículos!
plt.savefig('poluentes.png', dpi=300, bbox_inches='tight')
plt.show()

"""## Análise da contagem de medições por ano


"""

#Realizando a contagem de medições por mês
dados['Mês'] = dados['DataHora'].dt.month
dados['Ano'] = dados['DataHora'].dt.year
medicoes_anuais = dados.groupby('Ano').size().reset_index(name='Contagem')
print(medicoes_anuais)
plt.bar(medicoes_anuais['Ano'],medicoes_anuais['Contagem'])
plt.title('Contagem de medições por ano')
plt.xlabel('Ano')
plt.ylabel('Número de medições')
plt.savefig('contagem.png', dpi=300, bbox_inches='tight')
plt.show()

"""## Análise do poluente MP10

"""

#Realizando o cálculo de média diário do MP10
mp10 = (dados['Poluente'] == 'MP10')
dados_mp10 = dados[mp10]
dados['Data'] = dados['DataHora'].dt.date
media_diaria = dados_mp10.groupby('Data')['Valor'].mean().reset_index()
media_diaria.rename(columns={'Valor': 'MediaMP10'}, inplace=True)
mp10_graph = plt.plot(media_diaria['Data'], media_diaria['MediaMP10'], color='blue')
plt.title('Média Diária de MP10 em São Paulo')
plt.xlabel('Data')
plt.ylabel('MP10 (ug/m3)')

plt.savefig('grafico_mp10.png', dpi=300, bbox_inches='tight')
plt.show()

media_diaria['Data'] = pd.to_datetime(media_diaria['Data'])
media_diaria['Ano'] = media_diaria['Data'].dt.year
media_anual = media_diaria.groupby('Ano')['MediaMP10'].mean().reset_index()
print(media_anual)
media_anual.columns = ['Ano', 'MediaMP10']
plt.plot(media_anual['Ano'], media_anual['MediaMP10'])
plt.title('Média anual do Poluente MP10')
plt.xlabel('Ano')
plt.ylabel('Média')

plt.savefig('grafico_mp10_anual.png', dpi=300, bbox_inches='tight')
plt.show()

"""## Análise do ozônio (O₃) // Segundo maior poluente

"""

contagem_o3 = dados['Poluente'] == 'O3'
dados_o3 = dados[contagem_o3]
dados_o3.value_counts('Poluente')
dados_o3['Data'] = pd.to_datetime(dados_o3['DataHora']).dt.date
media_diaria_o3 = dados_o3.groupby('Data')['Valor'].mean().reset_index()
plt.plot(media_diaria_o3['Data'], media_diaria_o3['Valor'], color='red')
plt.title('Média Diária de O₃ em São Paulo')
plt.xlabel('Data')
plt.ylabel('O₃ (µg/m³)')

"""## Análise comparativa entre os dois primeiros poluentes

###Relembrando:
### - O3 é um gás agressivo que penetra nas vias respiratórias, reduzindo o funcionamento pulmonar e causando danos a ele. Além disso, o poluente O3 é formado por reações com poluentes primários, como óxidos de nitrogênio;
### - MP10 é causado por processos industriais, veículos automotores, queimadas, poeira do solo e atividades agrícolas.

### Distribuição da média anual dos poluentes MP10 e O₃ (2015–2021)
Observamos uma **tendência de queda nos níveis de O₃ (ozônio troposférico)** entre 2015 e 2017, com posterior estabilização até 2021. Essa redução pode estar relacionada a **menores emissões de precursores do ozônio**, como os óxidos de nitrogênio (NOx) e compostos orgânicos voláteis (COVs), frequentemente associados ao tráfego urbano e à indústria. Além disso, fatores climáticos e medidas restritivas durante a pandemia também podem ter influenciado.
Em contrapartida, o **MP10 apresenta uma tendência de crescimento** ao longo dos anos, o que pode estar associado ao **aumento da frota de veículos, obras urbanas e condições climáticas secas** que favorecem a concentração de partículas no ar. Por ser um poluente diretamente emitido, o MP10 é um indicador mais direto da atividade urbana e do tráfego intenso.
"""

filtro = dados['Poluente'].isin(['MP10', 'O3'])
dados_filtrados = dados[filtro]
media_anuais = dados_filtrados.groupby(['Ano', 'Poluente'])['Valor'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.lineplot(data=media_anuais, x='Ano', y='Valor', hue='Poluente', marker='o')
plt.title('Média anual dos poluentes MP10 e O₃ em São Paulo (2015–2021)')
plt.ylabel('Concentração média (µg/m³)')
plt.grid(True)
plt.tight_layout()
plt.show()

"""### Distribuição anual dos poluentes MP10 e O₃ (2015–2021)

O boxplot permite visualizar a dispersão dos dados ao longo dos anos. O **MP10 apresenta maior variabilidade**, com vários valores extremos (outliers), o que indica picos de concentração ao longo do tempo. Isso é esperado, pois o MP10 está fortemente ligado à atividade urbana direta, como o trânsito e obras.

O **O₃, por outro lado, mostra uma distribuição mais concentrada**, com menos variações bruscas ano a ano. Essa estabilidade reforça a natureza secundária do ozônio, formado a partir de reações químicas e menos sujeito a emissões diretas pontuais.

Além disso, observa-se que a **mediana do MP10 manteve-se relativamente constante ou em leve crescimento**, enquanto o O₃ estabilizou após uma queda entre 2015 e 2017.

"""

plt.figure(figsize=(12, 6))
sns.boxplot(data=dados_filtrados, x='Ano', y='Valor', hue='Poluente')
plt.title('Distribuição anual dos poluentes MP10 e O₃ (2015–2021)')
plt.ylabel('Concentração (µg/m³)')
plt.xlabel('Ano')
plt.legend(title='Poluente')
plt.grid(True)
plt.tight_layout()
plt.show()

"""##Pandemia x Poluentes

###Durante a pandemia de COVID-19, diversos estudos relataram redução da poluição do ar em áreas urbanas. Neste etapa, analisamos os níveis médios de todos os poluentes monitorados em São Paulo entre 2019 e 2021.
"""

dados_pandemia = dados[dados['Ano'].between(2019, 2021)]
media_anuais_todos = dados_pandemia.groupby(['Ano', 'Poluente'])['Valor'].mean().reset_index()
plt.figure(figsize=(14, 7))
sns.lineplot(data=media_anuais_todos, x='Ano', y='Valor', hue='Poluente', marker='o')
plt.title('Comparativo da média anual de todos os poluentes (2019–2021)')
plt.xlabel('Ano')
plt.ylabel('Concentração média (µg/m³)')
plt.legend(title='Poluente')
plt.grid(True)
plt.tight_layout()
plt.show()

pivot = media_anuais_todos.pivot(index='Poluente', columns='Ano', values='Valor')
plt.figure(figsize=(10, 6))
sns.heatmap(pivot, annot=True, fmt=".1f", cmap="coolwarm")
plt.title('Médias anuais de concentração dos poluentes (2019–2021)')
plt.ylabel('Poluente')
plt.xlabel('Ano')
plt.tight_layout()
plt.show()

"""## 🦠 Impacto da Pandemia na Poluição (2019–2021)

Durante o período de pandemia, especialmente em 2020, São Paulo passou por diversas restrições de circulação, lockdowns e queda nas atividades industriais. Isso teve reflexo direto nos níveis de alguns poluentes:

- O **CO (monóxido de carbono)** apresentou a maior queda, reforçando seu vínculo com o tráfego urbano.
- Outros poluentes como **PTS, NO₂ e FMC** também caíram em 2020, mas voltaram a subir ou estabilizaram em 2021.
- Já o **O₃ (ozônio)** se manteve estável, como esperado de um poluente secundário, que depende de reações atmosféricas.
- **MP10 e MP2.5** mostraram variação mínima — o que pode indicar que fontes como poeira, obras e queima de biomassa continuaram ativas mesmo durante restrições.

Esses dados mostram, com base científica, que **mudanças no comportamento urbano geram impacto quase imediato na qualidade do ar.**
"""